version: '3.9'
name: 'funtech_dev'

services:
  redis:
    image: redis:7-alpine
    command: redis-server
    expose:
      - "6379"
    volumes:
      - redis_value:/data

  postgres:
    image: postgres:14
    volumes:
      - postgres_value:/var/lib/postgresql/data
    env_file:
      - ./.env
    expose:
      - "5432"
    depends_on:
      - redis

  frontend:
    image: standup1990/funtech-front:latest
    restart: always
    command: "/bin/sh -c 'while :; do sleep 1h; done'"
    expose:
      - "3000"
    depends_on:
      - postgres

  backend:
    image: standup1990/event:latest
    restart: always
    env_file:
      - ./.env
    volumes:
      - static_value:/event_app/static/
      - media_value:/event_app/media/
    expose:
      - "8000"
    depends_on:
      - frontend

  nginx:
    image: nginx:1.23.4
    ports:
      - "80:80"
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/nginx/configs:/etc/nginx/conf.d:ro
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
      - frontend
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

volumes:
  postgres_value:
  redis_value:
  static_value:
  media_value:
